### ISSUE TITLE
Clicking doesn't work when deployed to a mobile device using Cordova

### ISSUE THREAD

**Issue by mr-e-** [keppelen/react-facebook-login#100]
The button does nothing when clicked = onClick event is simply not fired and no javascript error is listed.

**Comment by RobertSheaO** [comment]
Same in mobile Safari

**Comment by RobertSheaO** [comment]
It appears that it's an issue with the pop-under that loads as part of the `setFbAsyncInit` function. After turning off my pop-up blocker and content blocker in Mobile Safari, it works.

**Comment by DJTouchette** [comment]
I'm having this problem to on desktop chrome. Did anyone find a solution?

**Comment by tobitos** [comment]
Just in case it might be helpful to anybody: I also thought at first that the button is doing nothing at all on Mobile Safari until I realized the Facebook SDK is using a different redirect based login flow if it cannot open a popup. This might look as if the button is doing nothing at all, because it's really fast if you're already logged into Facebook.

After the redirect you should be back on your own website with a `code` URL parameter that (together with your Facebook App Secret) can be used to retrieve an `accessToken` from the Facebook API.
