### ISSUE TITLE
check if user is logged in

### ISSUE THREAD

**Issue by iliran11** [keppelen/react-facebook-login#125]
hi,
i want to check if the user is logged in, and based on it - show/hide  the react-facebook-login component.
* is the api of this component provide a way to check if the user is already logged?  without enabling the 'autoLoad' ?
* is there a need to open a pull request to add this?

**Comment by edsilfer** [comment]
+1

**Comment by iliran11** [comment]
please check my new repository.
it answers some of the questions and i actively maintain it.
you can help too (:

https://github.com/iliran11/facebook-login-react

**Comment by keppelen** [comment]
@iliran11  you can use `autoLoad` for it. But if there you other idea, send a PR :)

**Comment by swapydapy** [comment]
@keppelen Yes, **autoLoad** makes sense. But in case if not logged in, it also tries to show that popup which is very intrusive. Also since popups are blocked by default, browser shows that ugly icon, which looks like as if this-website-tried-todo-something-fishy. I feel what we need is that it should just check for loggedIn status and trigger the callback with the response. Do you think this makes sense?

Btw, thanks for this amazing react implementation for FB login button :)
