### ISSUE TITLE
Scope is not working

### ISSUE THREAD

**Issue by itzikbenh** [keppelen/react-facebook-login#35]
I only get the ID, name, and accessToken. Scope is not taking effect at all.

**Comment by Tolomeo** [comment]
That's not that the scope param is not working, it seems instead that the readme fails to list a parameter "fields" which you can pass to the component to configure the response object.
I've found it having a look at src/facebook.js, where the defaultProps.fields class property is set to 'name' so that the call returns only a concatenation of first name and last name.
You can obtain first name, last name and email passing the prop to the component like this:
`<FacebookLogin appId="..." fields="first_name,last_name,email"/>`

**Comment by ammichael** [comment]
I'm using `<FacebookLogin 'fields='name,email,picture.width(80).height(80)' ... />`, but I never receive the email in the response

 =(

**Comment by choosenvictim** [comment]
I am facing the same issue of not getting email in the response.
Here is my Component:
```
<FacebookLogin
    ...
    fields="name,email,picture"
    scope="public_profile,email"
    ...
/>
```
I tried all combination, with or without scope and its not working at all.

**Comment by tkoar** [comment]
If you look at the facebook OAuth permissions docs, they actually warn about asking for a user's email. The problem may be that the user does not have their email on facebook. checkout the documentation: https://developers.facebook.com/docs/facebook-login/permissions/#reference-email
