### ISSUE TITLE
Error after Install

### ISSUE THREAD

**Issue by thesynthetic** [keppelen/react-facebook-login#4]
Any idea why it can't see React variable?

cument.getElementById("facebook-login"))},function(e,t,n){e.exports=React},fun
                                                                    ^
ReferenceError: React is not defined
    at Object.<anonymous> (/Users/Ryeguy/Documents/Projects/Books/node_modules/react-facebook-login/dist/facebook-login.js:1:578)
    at t (/Users/Ryeguy/Documents/Projects/Books/node_modules/react-facebook-login/dist/facebook-login.js:1:169)
    at Object.e.exports (/Users/Ryeguy/Documents/Projects/Books/node_modules/react-facebook-login/dist/facebook-login.js:1:326)
    at t (/Users/Ryeguy/Documents/Projects/Books/node_modules/react-facebook-login/dist/facebook-login.js:1:169)
    at /Users/Ryeguy/Documents/Projects/Books/node_modules/react-facebook-login/dist/facebook-login.js:1:284
    at Object.<anonymous> (/Users/Ryeguy/Documents/Projects/Books/node_modules/react-facebook-login/dist/facebook-login.js:1:289)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Ryeguy/Documents/Projects/Books/node_modules/node-jsx/index.js:26:12)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Ryeguy/Documents/Projects/Books/components/header.react.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Ryeguy/Documents/Projects/Books/node_modules/node-jsx/index.js:26:12)
    at Module.load (module.js:355:32)

**Comment by georgiana-gligor** [comment]
I'm getting this error as well

**Comment by arnaud** [comment]
:+1: same here

**Comment by cgarvis** [comment]
:+1: same here

**Comment by krejcon3** [comment]
+1

**Comment by danpantry** [comment]
This occurs because this module appears to rely on React being present in the global namespace (which it will be if loaded via browser). Obviously, this doesn't work in Node environments.

This is due to the `externals` setting in `webpack.config.js`. The way to fix is to either:

- Have React exposed in the global namespace (i.e, on `window`) - This breaks isomorphism without some tricks with `jsdom`

Or

- Instead of exporting the webpack compilation result, run a compilation using **babel** in the `prepublish` step - skip webpack entirely - then export the resultant component file there.

I'd recommend approach number 2; it's how I approached this issue.

Workaround is to use `require('react-facebook-login/facebook.jsx')`, but you'll need to enable the parsing of external modules with babel first.

**Comment by shampooj** [comment]
I am unable to set `window.React = React` if I import this module anywhere into my application. Any idea why that might be happening?

**Comment by hex** [comment]
Will this be fixed?

**Comment by lldata** [comment]
I had the same problem, using the https://github.com/erikras/react-redux-universal-hot-example starter.
The problem comes from using server side rendering, so a simple solution is just to disable that.
I this particular starter you have to set __DISABLE_SSR__ = true in server.js

To make it work I also cleaned up the js, to match the starters es6 styleguide:
/*eslint-disable*/
import React, {Component, PropTypes} from 'react';

export default class Facebook extends Component {
  static propTypes = {
    loginHandler: PropTypes.func.isRequired,
    appId: PropTypes.string.isRequired,
    xfbml: PropTypes.string,
    scope: PropTypes.string.isRequired,
    fields: PropTypes.string.isRequired,
    styles: PropTypes.string,
    callToAction: PropTypes.string,
    class: PropTypes.string,
    autoLoad: PropTypes.bool
  }

  constructor() {
    super();
    this.handleClick = this.handleClick.bind(this);
    this.checkLoginState = this.checkLoginState.bind(this);
    this.responseApi = this.responseApi.bind(this);
  }

  componentDidMount() {
    window.fbAsyncInit = function() {
      FB.init({
        appId: this.props.appId || '',
        xfbml: this.props.xfbml || false,
        version: 'v2.5'
      });

      if ( this.props.autoLoad ) {
        FB.getLoginStatus(function(response) {
          this.checkLoginState(response);
        }.bind(this));
      }
    }.bind(this);

    // Load the SDK asynchronously
    (function(doc, str, id) {
      const fjs = doc.getElementsByTagName(str)[0];
      if (doc.getElementById(id)) {return;}
      const js = doc.createElement(str);
      js.id = id;
      js.src = '//connect.facebook.net/pt_BR/sdk.js';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  }

  responseApi( authResponse ) {
    FB.api('/me?fields='+this.props.fields, function(response) {
      response.status = 'connected';
      response.accessToken = authResponse.accessToken;
      response.expiresIn = authResponse.expiresIn;
      response.signedRequest = authResponse.signedRequest;

      if ( this.props.loginHandler ) {
        this.props.loginHandler( response );
      }
    }.bind(this));
  }

  checkLoginState(response) {
    if (response.authResponse) {
      this.responseApi(response.authResponse);
    } else {
      if ( this.props.loginHandler ) {
        this.props.loginHandler( { status: response.status } );
      }
    }
  }

  handleClick() {
    const valueScope = this.props.scope || 'public_profile, email, user_birthday';
    console.log('asking for scope: ' + valueScope);
    FB.login(this.checkLoginState, { scope: valueScope });
  }

  render() {
    require('./facebook.scss');
    return (
      <div>
        <button className={ this.props.class ? this.props.class : 'facebook-login'} onClick={ this.handleClick }>
            { this.props.callToAction ? this.props.callToAction : 'Login with Facebook'}
        </button>
        <div id="fb-root"></div>
      </div>
    );
  }
}

... and to actually get the email back from facebook, I had to add a "fields" query to the /me api call and make that a required prop.

          <Facebook
            appId="12345678901234567"
            class="facebook-login"
            scope="public_profile, email, user_birthday"
            fields="id,name,email,birthday"
            loginHandler={ this.resultFacebookLogin } />

It is too late in the evening to create a pull request, but I hope the maintainer can use this.

**Comment by keppelen** [comment]
@hex Please, test this fixed?

**Comment by keppelen** [comment]
@lldata you can test now with server side rendering?

**Comment by lldata** [comment]
Hi, as long as you load the facebook sdk the way you do, I don't think your component can ever be work on the server. On the serverside there is no "window.FB" and creating a script element dynamically will not do anything.

I think the way forward is to integrate a package like this:
https://www.npmjs.com/package/facebook-nodejs-sdk

**Comment by AmaliDeveloper** [comment]
You can get the solution here Facebook SDK connect [Link](https://youtu.be/xKC5pFEpH2A)
