### ISSUE TITLE
error: FB.login() called before FB.init()

### ISSUE THREAD

**Issue by dmorrow** [keppelen/react-facebook-login#71]
Seems to be related to reauthenticate.
Setting reauthenticate={false} and changing settings for autoLoad don't seem to make a difference.
This issue doesn't appear in 3.2.0

**Comment by dmorrow** [comment]
The solution appears to be both authLoad={true} and reauthenticate={true} need to be true.

**Comment by ArekRado** [comment]
I changed this line:

`window.fbAsyncInit =() => {`

to this:

`window.fbAsyncInit = function() {`

**Comment by Pasta** [comment]
@dmorrow how did you end up fixing this problem?

**Comment by dmorrow** [comment]
@Pasta See my comment above - I don't exactly remember, but it seems that setting `authLoad` and `reauthenticate` to true solved the issue.

**Comment by Pasta** [comment]
@dmorrow I tried but didn't change anything. 

@keppelen did you see this problem before?

**Comment by Steinarthor** [comment]
I'm having the same issue :'( Did anyone manage to fix this ? Works fine in dev mode but once in prod everything goes BOOM!

**Comment by aneurysmjs** [comment]
yeah, even I set it with  'autoLoad' and 'reaunthenticate' to true it keeps printing the same issue,
``` javacript
<FacebookLogin
  appId="xxxxxxxxxxxxxxx"
  autoLoad={true}
  reauthenticate={true}
  fields="name,email,picture"
  onClick={this.componentClicked}
  callback={this.responseFacebook}
/>
```
``` javascript
 error: FB.login() called before FB.init()
```

**Comment by sergkulikovskyi** [comment]
any updates?

**Comment by Kelvne** [comment]
I'm having this problem after using the library for months. Suddenly something broke it.

**Comment by pho3nixf1re** [comment]
This suddenly started happening to me as well. It was working fine until today. Happening in all environments (local, staging, prod).

**Comment by globad** [comment]
I'm sorry. I've found that the problem was in **missing application ID**.

Some details. I'm using Next.js, application Id was set by `next.config.js`. Usually all changes in the code are applied automatically with HMR. But in case of config settings this does not work. So you need to restart Next.js application to see the changes. After that the problem was solved.
I needed to build my own FacebookLogin to find it out :-D. After it was finished, I've found the error of missing Id and fixed it. Then I've rolled back to react-facebook-login and it has worked!

Notice | Propose
Handle this case (of missing or invalid app ID) and show proper error message. In my case there was no any PropTypes warning message (I guess it is because of prod. build) that could pointed me to the source of the problem.
